site_name: HAIHA'S BLOG

theme:
  name: material
  icon:
    logo: fontawesome/solid/brain
    # favicon: assets/meta/brain-solid.png
  font:
    text: "Sans-serif"
    code: "Sans-serif"
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: fontawesome/solid/sun  # Thay đổi thành biểu tượng mặt trời
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: fontawesome/solid/moon  # Biểu tượng mặt trăng cho chế độ dark mode
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: fontawesome/solid/sun  # Biểu tượng mặt trời cho chế độ light mode
        name: Switch to light mode

plugins:
  - tags:
      tags_file: tags.md

features:
  - search.suggest
  - search.highlight
  - navigation.footer
  - content.tabs.link

copyright: Copyright &copy; 2024 haihanguyen
